-- begin RIOC_SPLIT_MAPS
alter table RIOC_SPLIT_MAPS add constraint FK_RIOC_SPLIT_MAPS_ON_SUBMISSION foreign key (SUBMISSION_ID) references RIOC_SUBMISSION(ID) on delete CASCADE^
create index IDX_RIOC_SPLIT_MAPS_ON_SUBMISSION on RIOC_SPLIT_MAPS (SUBMISSION_ID)^
-- end RIOC_SPLIT_MAPS
-- begin RIOC_ERROR
alter table RIOC_ERROR add constraint FK_RIOC_ERROR_ON_SUBMISSION foreign key (SUBMISSION_ID) references RIOC_SUBMISSION(ID)^
create index IDX_RIOC_ERROR_ON_SUBMISSION on RIOC_ERROR (SUBMISSION_ID)^
-- end RIOC_ERROR
-- begin RIOC_STATUS_CHANGE
alter table RIOC_STATUS_CHANGE add constraint FK_RIOC_STATUS_CHANGE_ON_SUBMISSION foreign key (SUBMISSION_ID) references RIOC_SUBMISSION(ID)^
create index IDX_RIOC_STATUS_CHANGE_ON_SUBMISSION on RIOC_STATUS_CHANGE (SUBMISSION_ID)^
-- end RIOC_STATUS_CHANGE
-- begin RIOC_NOTIFICATION_SLOT
alter table RIOC_NOTIFICATION_SLOT add constraint FK_RIOC_NOTIFICATION_SLOT_ON_SUBMISSION foreign key (SUBMISSION_ID) references RIOC_SUBMISSION(ID)^
create index IDX_RIOC_NOTIFICATION_SLOT_ON_SUBMISSION on RIOC_NOTIFICATION_SLOT (SUBMISSION_ID)^
-- end RIOC_NOTIFICATION_SLOT
-- begin RIOC_SUBMISSION
alter table RIOC_SUBMISSION add constraint FK_RIOC_SUBMISSION_ON_INTENDED_RECEPIENT foreign key (INTENDED_RECEPIENT) references RIOC_RECEPIENT(ID)^
alter table RIOC_SUBMISSION add constraint FK_RIOC_SUBMISSION_ON_PURPOSE_OF_SUBMISSION foreign key (PURPOSE_OF_SUBMISSION) references RIOC_LINEOF_BUSINESS(ID)^
alter table RIOC_SUBMISSION add constraint FK_RIOC_SUBMISSION_ON_HIHCONFIGID foreign key (HIHCONFIGID) references RIOC_HIH_CONFIGURATION(ID)^
create index IDX_RIOC_SUBMISSION_ON_INTENDED_RECEPIENT on RIOC_SUBMISSION (INTENDED_RECEPIENT)^
create index IDX_RIOC_SUBMISSION_ON_PURPOSE_OF_SUBMISSION on RIOC_SUBMISSION (PURPOSE_OF_SUBMISSION)^
create index IDX_RIOC_SUBMISSION_ON_HIHCONFIGID on RIOC_SUBMISSION (HIHCONFIGID)^
-- end RIOC_SUBMISSION
-- begin RIOC_DOCUMENT
alter table RIOC_DOCUMENT add constraint FK_RIOC_DOCUMENT_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID)^
alter table RIOC_DOCUMENT add constraint FK_RIOC_DOCUMENT_ON_SUBMISSIONID foreign key (SUBMISSIONID) references RIOC_SUBMISSION(ID) on delete CASCADE^
create index IDX_RIOC_DOCUMENT_ON_FILEDESCRIPTORID on RIOC_DOCUMENT (FILEDESCRIPTORID)^
create index IDX_RIOC_DOCUMENT_ON_SUBMISSIONID on RIOC_DOCUMENT (SUBMISSIONID)^
-- end RIOC_DOCUMENT
-- begin RIOC_PROVIDERS
alter table RIOC_PROVIDERS add constraint FK_RIOC_PROVIDERS_ON_SUBMISSION foreign key (SUBMISSION_ID) references RIOC_SUBMISSION(ID) on delete SET NULL^
create index IDX_RIOC_PROVIDERS_ON_SUBMISSION on RIOC_PROVIDERS (SUBMISSION_ID)^
-- end RIOC_PROVIDERS
